// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DinosAPI.Migrations
{
    [DbContext(typeof(DinosaurContext))]
    [Migration("20240821135540_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Dinosaur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Feed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dinosaurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feed = "Carnivore",
                            Height = "4m",
                            Length = "14m",
                            Location = "North America",
                            Name = "T-rex",
                            Period = "Crétacé",
                            Weight = "7t"
                        },
                        new
                        {
                            Id = 2,
                            Feed = "Carnivore",
                            Height = "2m",
                            Length = "3m",
                            Location = "USA, Canada, Mongolie",
                            Name = "Vélociraptor",
                            Period = "Crétacé",
                            Weight = "136kg"
                        },
                        new
                        {
                            Id = 3,
                            Feed = "Herbivore",
                            Height = "20m",
                            Length = "30m",
                            Location = "North America, Portugal, Tanzanie",
                            Name = "Brachiosaurus",
                            Period = "Jurassique",
                            Weight = "60t"
                        },
                        new
                        {
                            Id = 4,
                            Feed = "Carnivore",
                            Height = "2m",
                            Length = "6m",
                            Location = "Arizona",
                            Name = "Dilophosaurus",
                            Period = "Jurassique",
                            Weight = "1t"
                        },
                        new
                        {
                            Id = 5,
                            Feed = "Herbivore",
                            Height = "2m",
                            Length = "8m",
                            Location = "Mongolie",
                            Name = "Gallimimus",
                            Period = "Crétacé",
                            Weight = "440kg"
                        },
                        new
                        {
                            Id = 6,
                            Feed = "Herbivore",
                            Height = "3m",
                            Length = "10m",
                            Location = "North America",
                            Name = "Triceratops",
                            Period = "Crétacé",
                            Weight = "10t"
                        },
                        new
                        {
                            Id = 7,
                            Feed = "Herbivore",
                            Height = "4m",
                            Length = "10m",
                            Location = "North America",
                            Name = "Parasaurolophus",
                            Period = "Crétacé",
                            Weight = "5t"
                        },
                        new
                        {
                            Id = 8,
                            Feed = "Carnivore",
                            Height = "30cm",
                            Length = "1m",
                            Location = "Europe",
                            Name = "Compsognathus",
                            Period = "Jurassique",
                            Weight = "3,5kg"
                        },
                        new
                        {
                            Id = 9,
                            Feed = "Herbivore",
                            Height = "4m",
                            Length = "9m",
                            Location = "Morrison Formation",
                            Name = "Stegosaurus",
                            Period = "Jurassique",
                            Weight = "4t"
                        },
                        new
                        {
                            Id = 10,
                            Feed = "Carnivore",
                            Height = "7m",
                            Length = "15m",
                            Location = "North Africa",
                            Name = "Spinosaurus",
                            Period = "Crétacé",
                            Weight = "10t"
                        },
                        new
                        {
                            Id = 11,
                            Feed = "Carnivore",
                            Height = "20m",
                            Length = "2m",
                            Location = "Sea of Europe, North America, Africa, Australia, New-Zealand",
                            Name = "Mosasaurus",
                            Period = "Crétacé",
                            Weight = "10t"
                        },
                        new
                        {
                            Id = 12,
                            Feed = "Carnivore",
                            Height = "2,5m",
                            Length = "9,5m",
                            Location = "England, Spain",
                            Name = "Baryonyx",
                            Period = "Crétacé",
                            Weight = "2,5t"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
